export const NUM_OF_GUESSES_ALLOWED = 6;
export const CHARACTERS = [
  { letter: 'q', status: undefined },
  { letter: 'w', status: undefined },
  { letter: 'e', status: undefined },
  { letter: 'r', status: undefined },
  { letter: 't', status: undefined },
  { letter: 'y', status: undefined },
  { letter: 'u', status: undefined },
  { letter: 'i', status: undefined },
  { letter: 'o', status: undefined },
  { letter: 'p', status: undefined },
  { letter: 'a', status: undefined },
  { letter: 's', status: undefined },
  { letter: 'd', status: undefined },
  { letter: 'f', status: undefined },
  { letter: 'g', status: undefined },
  { letter: 'h', status: undefined },
  { letter: 'j', status: undefined },
  { letter: 'k', status: undefined },
  { letter: 'l', status: undefined },
  { letter: 'z', status: undefined },
  { letter: 'x', status: undefined },
  { letter: 'c', status: undefined },
  { letter: 'v', status: undefined },
  { letter: 'b', status: undefined },
  { letter: 'n', status: undefined },
  { letter: 'm', status: undefined },
];
